### ISSUE TITLE
Way to specify alarm 'sound'?

### ISSUE THREAD

**Issue by bowernite** [vitorgalvao/shrieking-chimes-workflow#2]
Thanks for the great work on this workflow 💛

Is there a way to specify the 'sound' the alarm makes? i.e. I'd like to not use the default `Beacon` sound, and instead be silent or use the `Not playing` option that the app gives you.

**Comment by vitorgalvao** [comment]
Thank you for the kind words.

Create a new alarm manually in the Clock app and choose whatever sound you want. You can then delete it. The next time you make an alarm with the workflow, it’ll use that sound.

**Comment by bowernite** [comment]
Gotcha, thanks!

It seems like if I use `Stop Playing`, macOS doesn't spawn a notification from notification center. I know this is kind of out of scope of this workflow, but do you know if there's a way to have a timer that spawns the notification, but without any sound? 🙂
